<?php
namespace App\Http\Controllers;
use App\Events\{BotJoined,CanvasCleared,PlayerJoined,PlayerLeft}; use App\Jobs\{BotDrawJob,BotJoinJob}; use App\Models\{Background,DrawingSession,Player,RecordedStroke,Report}; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB; use Illuminate\Support\Str;
class SessionController extends Controller {
 private function newCode(): string {do{$c=strtoupper(Str::random(6));}while(DrawingSession::where('code',$c)->exists());return $c;}
 private function activeHuman(DrawingSession $s,string $ip): ?Player{return $s->players()->where('ip_address',$ip)->where('is_bot',false)->whereNull('left_at')->first();}
 public function create(Request $r){$s=DB::transaction(function()use($r){$s=DrawingSession::create(['code'=>$this->newCode(),'background_id'=>Background::inRandomOrder()->value('id'),'status'=>'waiting']);$s->players()->create(['ip_address'=>$r->ip(),'is_bot'=>false,'last_activity_at'=>now(),'joined_at'=>now()]);return $s;});event(new PlayerJoined($s->code,$r->ip()));BotJoinJob::dispatch($s->id)->delay(now()->addSeconds(60));return redirect()->route('session.show',$s->code);}
 public function playWithBot(Request $r){$s=DB::transaction(function()use($r){$s=DrawingSession::create(['code'=>$this->newCode(),'background_id'=>Background::inRandomOrder()->value('id'),'status'=>'active']);$s->players()->create(['ip_address'=>$r->ip(),'is_bot'=>false,'last_activity_at'=>now(),'joined_at'=>now()]);$s->players()->create(['ip_address'=>null,'is_bot'=>true,'last_activity_at'=>now(),'joined_at'=>now()]);return $s;});event(new PlayerJoined($s->code,$r->ip()));event(new BotJoined($s->code));BotDrawJob::dispatch($s->id)->delay(now()->addSecond());return redirect()->route('session.show',$s->code);}
 public function join(Request $r){$d=$r->validate(['code'=>['required','string','size:6','regex:/^[A-Za-z0-9]{6}$/']]);$s=DrawingSession::where('code',strtoupper($d['code']))->whereIn('status',['waiting','active'])->first();if(!$s)return back()->with('error','Session code is invalid or ended.');if($this->activeHuman($s,$r->ip()))return redirect()->route('session.show',$s->code);$active=$s->players()->whereNull('left_at')->get();if($active->count()>=2 || $active->contains('is_bot',true))return back()->with('error','Session is full.');$s->players()->create(['ip_address'=>$r->ip(),'is_bot'=>false,'last_activity_at'=>now(),'joined_at'=>now()]);$s->update(['status'=>'active']);event(new PlayerJoined($s->code,$r->ip()));return redirect()->route('session.show',$s->code);}
 public function show(Request $r,string $code){$s=DrawingSession::with(['background','players'=>fn($q)=>$q->whereNull('left_at')])->where('code',strtoupper($code))->whereIn('status',['waiting','active'])->firstOrFail();$me=$this->activeHuman($s,$r->ip());abort_unless($me,403,'Join this session from the landing page first.');return view('session',['session'=>$s,'me'=>$me,'initialStrokes'=>$s->recordedStrokes()->orderBy('drawn_at')->get(['points','color','size'])]);}
 public function leave(Request $r,string $code){$s=DrawingSession::where('code',strtoupper($code))->firstOrFail();if($p=$this->activeHuman($s,$r->ip())){$p->update(['left_at'=>now()]);event(new PlayerLeft($s->code,$r->ip()));}if(!$s->players()->whereNull('left_at')->where('is_bot',false)->exists())$s->update(['status'=>'ended']);return redirect()->route('landing');}
 public function report(Request $r,string $code){$s=DrawingSession::where('code',strtoupper($code))->firstOrFail();$me=$this->activeHuman($s,$r->ip());abort_unless($me,403);$other=$s->players()->whereNull('left_at')->where('is_bot',false)->where('ip_address','!=',$r->ip())->first();if($other)Report::create(['session_id'=>$s->id,'session_code'=>$s->code,'reporter_ip'=>$r->ip(),'reported_ip'=>$other->ip_address]);$me->update(['left_at'=>now()]);event(new PlayerLeft($s->code,$r->ip()));return redirect()->route('landing')->with('message',$other?'Report submitted.':'You left the session. No human participant was available to report.');}
 public function clear(Request $r,string $code){$s=DrawingSession::where('code',strtoupper($code))->firstOrFail();abort_unless($this->activeHuman($s,$r->ip()),403);$s->recordedStrokes()->delete();event(new CanvasCleared($s->code));return response()->noContent();}
 public function recordStroke(Request $r,string $code){$s=DrawingSession::where('code',strtoupper($code))->firstOrFail();abort_unless($this->activeHuman($s,$r->ip()),403);$d=$r->validate(['points'=>'required|array|min:2|max:1000','points.*.x'=>'required|numeric','points.*.y'=>'required|numeric','color'=>['required','string','regex:/^#[0-9A-Fa-f]{6}$/'],'size'=>'required|integer|min:1|max:40','drawn_at'=>'nullable|date']);RecordedStroke::create(['session_id'=>$s->id,'player_ip'=>$r->ip(),'points'=>$d['points'],'color'=>$d['color'],'size'=>$d['size'],'drawn_at'=>$d['drawn_at']??now()]);return response()->noContent();}
 public function heartbeat(Request $r,string $code){$s=DrawingSession::where('code',strtoupper($code))->firstOrFail();$p=$this->activeHuman($s,$r->ip());abort_unless($p,403);$p->update(['last_activity_at'=>now()]);return response()->noContent();}
}
